= Lógica de Programação
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.3.0
:source-highlighter: coderay
:imagesdir: images
:allow-uri-read:
:safe: unsafe
:toc:

- https://palmas.ifto.edu.br/index.php/component/content/article?id=225[Curso Superior de Sistemas para Internet]
- http://www.ifto.edu.br[Instituto Federal de Educação, Ciência e Tecnologia do Tocantins]
- http://about.me/manoelcampos[Prof. Me. Manoel Campos da Silva Filho]

== Objetivo

Aprender os fundamentos para desenvolvimento de *programas* para solucionar problemas cotidianos.
Programas são executados em equipamentos como *computadores* e *smartphones*. Porém, atualmente podem ser encontrados em equipamentos como: 

- *televisores*: possibilitando interatividade dos telespectadores, fornecendo serviços de utilidade pública (como consulta de resultado das loterias e localização de postos de saúde), navegação na internet, jogos, etc;
- https://pt.wikipedia.org/wiki/Veículo_aéreo_não_tripulado[drones]: para permitir controlar aeronaves não tripuladas por meio de controle remoto ou mesmo permitir que elas possam voar de forma autônoma sem intervenção humana. 
- *veículos*: prover https://pt.wikipedia.org/wiki/Sistema_de_posicionamento_global[serviços de navegação por satélite (GPS)], entretenimento como players de vídeo e música e aplicações populares em smartphones como o Spotify, ou até mesmo permitir que carros possam ser guiados de forma autônoma, sem a intervenção do motorista, como é o caso de veículos da Tesla Motors. 

video::192179726[vimeo]

- robôs, semâforos, câmeras fotográficas, geladeiras, produtos de automação residencial como fechaduras eletrônicas, lâmpadas e uma série de produtos inteligentes como porteiros eletrônicos, relógios, balanças Wi-Fi, etc.


- https://kahoot.com
- http://exercism.io
- http://education.github.com

video::wek9VPTdMMM[youtube]
video::tmQpP_r9QsU[youtube]

Programas podem ser desenvolvidos como páginas de internet, para serem acessados a partir de um navegador em um smartphone, TV, computador, etc. Mas como já visto, podem ser criados como aplicações independentes para uso nestes mesmos dispositivos. 
 
Tais programas serão desenvolvidos utilizando-se *algoritmos* escritos em alguma *linguagem de programação*. 

ifdef::book[]
endif::book[]

== Motivação 

- Automatizar tarefas repetitivas que demandem tempo e/ou esforço, visando reduzir custos, tempo de finalização de tais tarefas e eficiência pela redução de erros humanos.
- 

== Aplicabilidade

- O uso de 

== Método de Avaliação